enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@vueuse/router@*":
    peerDependencies:
      vue: ^3.0.0-0 || ^2.6.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
