# If possible, overrides should go there!

# If you prefer to use geo IP databases from host, uncomment this block.

# services:
#   akvorado-orchestrator:
#     volumes:
#       - /usr/share/GeoIP:/usr/share/GeoIP:ro

# If you want to expose the service directly on port 80, uncomment this block.

# services:
#   traefik:
#     ports: !override
#       - 127.0.0.1:8080:8080/tcp
#       - 80:8081/tcp
